site_name: MoonLoader Wiki
site_description: Полная неофициальная документация, справочник API функций, опкодов и руководств по Lua-скриптингу для MoonLoader в SA-MP.
site_author: mgmoldova
site_url: https://mgmoldova.github.io/moonloader-wiki/ 
repo_url: https://github.com/mgmoldova/moonloader-wiki 
repo_name: mgmoldova/moonloader-wiki
edit_uri: edit/main/docs/

theme:
  name: material
  language: ru
  icon:
    repo: fontawesome/brands/github
  palette:
    # Светлая тема
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo # Благородный глубокий синий
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Перейти на темную тему
    # Темная тема
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Перейти на светлую тему

  features:
    - navigation.tabs          # Верхнее меню (как на современных сайтах)
    - navigation.sections      # Визуальное разделение бокового меню на блоки
    - navigation.top           # Кнопка быстрой прокрутки вверх
    - navigation.tracking      # URL меняется автоматически при скролле к заголовкам
    - navigation.indexes       # Позволяет делать разделы меню кликабельными страницами
    - search.suggest           # Живой поиск на лету
    - search.highlight         # Подсветка найденных слов
    - search.share             # Кнопка "поделиться результатом поиска"
    - content.code.copy        # Кнопка копирования кода
    - content.code.annotate    # Аннотации прямо в строках кода (очень удобно для разбора API)
    - content.action.edit      # Кнопка "Редактировать" на каждой странице
    - content.action.view      # Опционально: кнопка "Просмотреть исходник"
      
plugins:
  - search

markdown_extensions:
  - tables 
  - attr_list                  # Позволяет добавлять кастомные CSS-классы к тексту
  - def_list                   # Удобные списки определений
  - md_in_html                 # Позволяет смешивать HTML и Markdown, если нужно
  - pymdownx.highlight:        
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences       
  - pymdownx.tabbed:
      alternate_style: true    
  - admonition                 
  - pymdownx.details           
  - pymdownx.magiclink         # Автоматически делает "голые" ссылки кликабельными
  - pymdownx.emoji:            # Поддержка красивых нативных эмодзи (:sparkles:)
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg